// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4sCCmirE9XhVTCRQ7SWB3vV9XNVc_eKA',
    appId: '1:384538349694:web:4b1604641cd3588283c82f',
    messagingSenderId: '384538349694',
    projectId: 'test-e6251',
    authDomain: 'test-e6251.firebaseapp.com',
    storageBucket: 'test-e6251.firebasestorage.app',
    measurementId: 'G-M1W18SW8PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7lj-V6WticubTIj1g4zWsgNpPh5iIFW4',
    appId: '1:384538349694:android:f4ecf2fbf5f7b12383c82f',
    messagingSenderId: '384538349694',
    projectId: 'test-e6251',
    storageBucket: 'test-e6251.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37WE5hiVeCmyY1jDVSNqg_UA4vhjlYQE',
    appId: '1:384538349694:ios:dacf7f4153bd22bf83c82f',
    messagingSenderId: '384538349694',
    projectId: 'test-e6251',
    storageBucket: 'test-e6251.firebasestorage.app',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB37WE5hiVeCmyY1jDVSNqg_UA4vhjlYQE',
    appId: '1:384538349694:ios:dacf7f4153bd22bf83c82f',
    messagingSenderId: '384538349694',
    projectId: 'test-e6251',
    storageBucket: 'test-e6251.firebasestorage.app',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4sCCmirE9XhVTCRQ7SWB3vV9XNVc_eKA',
    appId: '1:384538349694:web:fa1f02100ac22eba83c82f',
    messagingSenderId: '384538349694',
    projectId: 'test-e6251',
    authDomain: 'test-e6251.firebaseapp.com',
    storageBucket: 'test-e6251.firebasestorage.app',
    measurementId: 'G-0DT6N80WFB',
  );
}
